### ISSUE TITLE
El Capitan support

### ISSUE THREAD

**Issue by gustavo-vendramini-oktagon** [myspaghetti/macos-virtualbox#260] opened 2020-07-05 15:56 UTC
To install El Capitan it is just add the https://swscan.apple.com/content/catalogs/others/index-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog ?

And add CFBundleShortVersionString 10.11 ?

Could you please give instructions? I would be very grateful.

**Comment by myspaghetti** [comment] 2020-07-05 16:42
Duplicate of issue #206 

>When you have a working installation of macOS, it's very easy to create installation media for any available version of macOS as early as Tiger. Versions up to 10.12 use asr restore and later versions use createinstallmedia

>Panther and earlier run on PowerPC.

>That said, I'm willing to accept pull requests that add more macOS versions.

Meanwhile, you can manually create a bootable installer of El Capitan and boot it.

**Closed by myspaghetti** 2020-07-05 16:42 UTC
Labels: duplicate, enhancement
