### ISSUE TITLE
$'\r' Error

### ISSUE THREAD

**Issue by ANILSRGT** [myspaghetti/macos-virtualbox#611] opened 2022-07-07 08:41 UTC
```
./macos-guest-virtualbox.sh: line 6: $'\r': command not found
./macos-guest-virtualbox.sh: line 15: $'\r': command not found
./macos-guest-virtualbox.sh: line 16: syntax error near unexpected token `$'{\r''
'/macos-guest-virtualbox.sh: line 16: `function set_variables() {
```

**Comment by myspaghetti** [comment] 2022-07-07 17:06
Duplicate of #28 , resolved as `won't fix`. [Probably on installation, `git` was set to convert newline characters `LF` to `CRLF`](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings). While I can [configure the repository to override local Git configuration](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings#per-repository-settings) I feel like respecting local settings is the correct solution.

Configure git to keep line endings or [download the script manually](https://raw.githubusercontent.com/myspaghetti/macos-virtualbox/master/macos-guest-virtualbox.sh).

**Closed by myspaghetti** 2022-07-07 17:06 UTC
Labels: duplicate, won't fix
