### ISSUE TITLE
$'\r': command not found

### ISSUE THREAD

**Issue by weclock-droid** [myspaghetti/macos-virtualbox#458] opened 2021-05-01 02:45 UTC
Is there a guide where I can learn how or what exactly to set this up? I've been trying my google-fu but so far I'm stuck here:

$ /home/user/macos-guest-virtualbox.sh
/home/user/macos-guest-virtualbox.sh: line 6: $'\r': command not found
/home/user/macos-guest-virtualbox.sh: line 15: $'\r': command not found
/home/user/macos-guest-virtualbox.sh: line 16: syntax error near unexpected token `$'{\r''
'home/user/macos-guest-virtualbox.sh: line 16: `function set_variables() {

**Comment by Masamune3210** [comment] 2021-05-01 02:47
whatever you downloaded the script in fuxed the line endings I think, download it raw from github and it should work a bit better

**Comment by myspaghetti** [comment] 2021-05-01 04:39
Duplicate of #28 , resolved as `won't fix`. [Probably on installation, `git` was set to convert newline characters `LF` to `CRLF`](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings). While I can [configure the repository to override local Git configuration](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings#per-repository-settings) I feel like respecting local settings is the correct solution.

Configure git to keep line endings or [download the script manually](https://raw.githubusercontent.com/myspaghetti/macos-virtualbox/master/macos-guest-virtualbox.sh).

**Closed by myspaghetti** 2021-05-01 04:39 UTC
Labels: duplicate, question

**Comment by lindeloev** [comment] 2021-05-06 19:33
For anyone coming here in the future: running `sed -i 's/\r$//' macos-guest-virtualbox.sh` removes the \r newline characters (answer from https://stackoverflow.com/a/32912867/1297830)
