### ISSUE TITLE
Cannot finish in ubuntu cpu AMD

### ISSUE THREAD

**Issue by alexisaraya** [myspaghetti/macos-virtualbox#212] opened 2020-05-24 17:30 UTC
Hi,

I have a ubuntu 18.10 in cpu AMD Phenom.

`Until the script completes, please do not interact with the virtual machine.`

in virtual machine see terminal

`LOG:EXITBS:START`

any idea for resume o fix installation ?

Tranks

**Comment by myspaghetti** [comment] 2020-05-24 18:07
Duplicate of issue #8. See the documentation about assigning CPU profiles.

**Closed by myspaghetti** 2020-05-24 18:07 UTC
Labels: bug, duplicate, non-script, won't fix
