### ISSUE TITLE
bash 5.1: unexpected EOF while looking for matching ')'

### ISSUE THREAD

**Issue by mziminski616** [myspaghetti/macos-virtualbox#472] opened 2021-05-29 03:14 UTC
I'm very new to the world of MacOS on a VM. I'm currently running this on my custom built desktop running Virtualbox. In order to run the script, I had to upgrade to Bash 4.x using homebrew. When I execute the script I get: 

```
bash: ./macos-guest-virtualbox.sh: line 689: unexpected EOF while looking for matching ')'

Error: Could not configure virtual machine "".
Please execute the stage configure_vm again before resuming the script as described in the documentation.
```

Can anyone help me with this?

**Comment by Masamune3210** [comment] 2021-05-29 03:37
the shell script seems to be busted from that error, try downloading it again, and make sure its not corrupted by anything

**Comment by myspaghetti** [comment] 2021-05-29 05:18
Hi, thanks for the bug report. Would you mind executing the following and attaching the resulting `debug.txt` file here?

`cp macos-guest-virtualbox.sh debug.txt`

**Comment by mziminski616** [comment] 2021-05-29 13:06
> Hi, thanks for the bug report. Would you mind executing the following and attaching the resulting `debug.txt` file here?
> 
> `cp macos-guest-virtualbox.sh debug.txt`

Thanks for getting back to me so quickly. Here's the debug file. 
[debug.txt](https://github.com/myspaghetti/macos-virtualbox/files/6564722/debug.txt)

**Comment by myspaghetti** [comment] 2021-05-29 18:13
I can't find bash `4.x` on homebrew, how did you install it?

**Comment by myspaghetti** [comment] 2021-05-29 18:14
I can't reproduce the bug with bash `5.x`, and I can't find bash `4.x` on homebrew, how did you install it?

**Comment by mziminski616** [comment] 2021-05-29 18:39
It was an entire 2 hour process actually.  When I first saw the error message about the incompatible bash version, I googled how to update bash on Mac. I found a result that said I could do it from homebrew with `brew install bash` but I first had to install homebrew from [homebrew.sh](https://homebrew.sh). I ran into an error because of xcode command line tools that I needed to manually install from Apple's official developer website.  Once all was said and done, I had homebrew installed and also the newer version of Bash. I'm not home right now so I can't take a screenshot of the version.

But how this all came to be is this: I wanted to build a Mac VM and I found a guide online to do that. But the VRAM is only 3mb instead of the 128mb that I gave virtualbox on my windows 10 host.  Is this what your scrip is intended for? Or am I completely missing the mark? How would you recommend that I achieve the task of the Mac VM? I know that this is probably outside the scope of the script, but at this point, I'm not sure I did anything right.

**Comment by myspaghetti** [comment] 2021-05-29 18:50
macOS reports the VRAM incorrectly. You can improve graphics performance by installing the VMWare Tools.

Back to the bug, I can reproduce it with bash version `5.1.8(1)-release (x86_64-apple-darwin17.7.0)`

Possibly it's specific to this version of bash. Currently investigating.

**Comment by myspaghetti** [comment] 2021-05-29 19:00
As a workaround you can run the script with `zsh` until someone figures out what's going on with bash 5.1.8

**Comment by mziminski616** [comment] 2021-05-29 19:26
Thanks for looking into this. Just one last question. How do I run it with zsh? I’m still very new to Unix command lines even though I was a cs major back in college.

**Comment by myspaghetti** [comment] 2021-05-30 01:24
Install zsh version 5.5 or higher, then execute `/usr/loca/bin/zsh -i macos-guest-virtualbox.sh`

**Comment by myspaghetti** [comment] 2021-05-30 02:38
Reproduced with bash `5.1.8(1)-release (x86_64-pc-linux-gnu)`

**Comment by myspaghetti** [comment] 2021-05-30 02:50
Reproduced with bash 5.1.0 though 5.1.8

**Comment by myspaghetti** [comment] 2021-05-30 03:17
Workaround in [version 0.98.9](https://github.com/myspaghetti/macos-virtualbox/commit/011c2236adfbd60e7ac063e0d6a9466c206a0caf)

I'm pretty sure this is a bash bug, both of these seem valid to me:
```
"$(command \
--option parameter
)"
```

```"
"$(
command \
--option parameter )"
````

**Comment by myspaghetti** [comment] 2021-05-30 03:18
Workaround in [version 0.98.9](https://github.com/myspaghetti/macos-virtualbox/commit/011c2236adfbd60e7ac063e0d6a9466c206a0caf)

I'm pretty sure this is a bash bug, both of these seem valid to me:
```
"$(command \
--option parameter )"
```

```"
"$(
command \
--option parameter
)"
````

**Comment by myspaghetti** [comment] 2021-05-30 05:09
Closing as non-script as this is likely not a bug with the script. Since the behavior is inconsistent with and without the `-i` option, I've [filed an issue with bash](https://savannah.gnu.org/support/?func=detailitem&item_id=110500)

**Closed by myspaghetti** 2021-05-30 05:09 UTC
Labels: bug
