### ISSUE TITLE
Remains on recovery screen after script finishes

### ISSUE THREAD

**Issue by IFcoltransG** [myspaghetti/macos-virtualbox#202] opened 2020-05-07 10:45 UTC
After the script finished (saying "That's it! Enjoy your virtual machine.") I am still presented with an almost blank virtual machine, the two terminals open and "Terminal" in the bar across the top. The script gives no information on what to do to get a proper Mac environment from here. Rebooting the VM takes me to Mac Recovery unhelpfully.

I'm on Manjaro linux using the default configuration for this script.

**Comment by IFcoltransG** [comment] 2020-05-07 11:18
Running "Startup Disk" from the Apple logo on the first drive also only returns me to recovery.

**Comment by myspaghetti** [comment] 2020-05-07 11:45
Did the `Preparing: ...%` in one of the terminals reach 100%? If so, you should have followed the instructions given by the script. If you're running VirtualBox 6.1 there are no further instructions, if you're running 6.0 or 5.2 you should have let the script power off the machine and detach the base system.
![preparing 001](https://user-images.githubusercontent.com/31696646/81290757-4b76c300-9071-11ea-8f54-56b34f2d4641.png)
![restart](https://user-images.githubusercontent.com/31696646/81290797-5a5d7580-9071-11ea-80f2-a513e5bc1b6a.png)


If that didn't happen, please attach a screenshot of the macOS guest when Terminal has finished executing the command, and attach the output of `./macos-guest-virtualbox troubleshoot > troubleshoot.txt`

**Comment by myspaghetti** [comment] 2020-05-07 11:49
Did the `Preparing: ...%` in one of the terminals reach 100%? If so, you should have followed the instructions given by the script. If you're running VirtualBox 6.1 there are no further instructions, if you're running 6.0 or 5.2 you should have let the script power off the machine and detach the base system.
![preparing 001](https://user-images.githubusercontent.com/31696646/81290757-4b76c300-9071-11ea-8f54-56b34f2d4641.png)
![restart](https://user-images.githubusercontent.com/31696646/81290797-5a5d7580-9071-11ea-80f2-a513e5bc1b6a.png)


If that didn't happen, please attach a screenshot of the macOS guest when Terminal has finished executing the command, and attach the output of the following command:
```
./macos-guest-virtualbox.sh troubleshoot > troubleshoot.txt
```

**Comment by myspaghetti** [comment] 2020-05-14 07:50
Closing until further details are provided.

**Comment by aaronjanse** [comment] 2020-05-24 05:05
I'm having this exact issue. I waited for the script to shutdown virtualbox etc.

[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/4672976/macOS_troubleshoot.txt)

**Comment by myspaghetti** [comment] 2020-05-24 07:14
@aaronjanse doesn't the script complain that it can't identify `BASH_VERSION`?

**Comment by aaronjanse** [comment] 2020-05-24 21:03
I just wrote up steps to exactly reproduce the issue. At the end, I realized: I manually ran the `populate_virtual_disks` phase but forgot the phases afterwards. Tysm!

**Closed** 2020-05-24 23:25 UTC
Labels: bug

**Comment by EnragedViper** [comment] 2020-06-20 15:40
Same issue. The virtual machine doesn't shut down by itself after the script finishes, and rebooting the VM brings me to Mac Recovery as well.

Screenshot of terminal windows (before I rebooted the VM):
![Screenshot (485)](https://user-images.githubusercontent.com/40548530/85205653-98a6af80-b314-11ea-8f39-1ae62258ff3f.png)

[macOS_troubleshoot.txt log file](https://pastebin.com/NiZcBHpY)

**Comment by myspaghetti** [comment] 2020-06-20 18:28
@EnragedViper all your installation files are correct and your configuration is correct. If I had to guess, there was an error copying the installer in the previous stage (`populate_virtual_disks`) but this error wasn't detected (because it occurred inside the virtual machine)

You should run the script again (no need to delete the downloaded installation files, they're correct) and keep an eye on the virtual machine while it's populating the bootable installation volume.

**Comment by EnragedViper** [comment] 2020-06-20 22:58
Huh, odd that it worked this time around. Thanks for the quick response.
