### ISSUE TITLE
Unable to install on Macbook Pro 2011

### ISSUE THREAD

**Issue by benze** [myspaghetti/macos-virtualbox#349] opened 2020-12-07 05:49 UTC
I've got an old Macbook Pro 2011 that is running High Sierra (10.13.6).  I've got VirtualBox 6.1.16 installed and running.

I've tried to run the install script to install Catalina, but the VM fails to boot.  I have tried all the profiles listed in the `CPU profiles and CPUID settings`, but none of the 6 options were able to boot succesfully.

Is there anything I can attempt, or is this just a case that my host CPU is too old and unsupported in Catalina and hence there is no way to get it to work in a VM?

**Comment by myspaghetti** [comment] 2020-12-08 06:41
Marking as duplicate of  #351

**Closed by myspaghetti** 2020-12-08 06:41 UTC
Labels: question
