### ISSUE TITLE
VirtualBox error - {vm name} is not running

### ISSUE THREAD

**Issue by MilitPatel** [myspaghetti/macos-virtualbox#590] opened 2022-03-16 17:30 UTC
Hi,
I've been using this script for quite a few months to make macos guest virtualboxes, and today, I tried running the script, like usual, and right before it does the automated recognition of the interface, the VirtualBox closes, and it loops an error that the {name of virtualbox} is not running.
Is there a specific reason for this or am I just doing something wrong?

**Comment by MilitPatel** [comment] 2022-03-16 17:31
may I add, it worked before using this same PC, and CPU, so I do not believe it is a CPU problem, but I could definitely be wrong.

**Comment by myspaghetti** [comment] 2022-03-16 17:52
Hi, thanks for the bug report. Are you running [the latest version of the script](https://raw.githubusercontent.com/myspaghetti/macos-virtualbox/master/macos-guest-virtualbox.sh)?

**Comment by MilitPatel** [comment] 2022-03-16 17:56
Yes, just downloaded newest version of script, ran it on 6.(something) VirtualBox and then now running Version 6.1.32 r149290, with an i5-10300h

**Comment by myspaghetti** [comment] 2022-03-21 13:21
Possibly a VirtualBox issue, I will investigate but probably not in the near future, sorry.

**Comment by myspaghetti** [comment] 2022-04-22 04:58
Sorry, haven't been able to reproduce the issue. My guess is that the required virtual disks were not created successfully, so the VM powers off immediately after being started. The script should fail gracefully when the disks can't be attached, but it does not detect anything if they're attached but corrupt or incomplete. Is there any indication that `create_bootable_installer_virtual_disk` failed?

**Comment by myspaghetti** [comment] 2022-05-09 19:28
Closing, with apologies, until further info is available, since I don't plan on investigating further for the time being.

**Closed by myspaghetti** 2022-05-09 19:28 UTC
Labels: bug
