### ISSUE TITLE
BUG crushes on cygwin (dos encoding)

### ISSUE THREAD

**Issue by MontrealSergiy** [myspaghetti/macos-virtualbox#390] opened 2021-01-21 08:58 UTC
Crushes on cygwin (though was tested ) but runs up to install coreutils on git-bash (mingw64 based)
```
/cygdrive/d/mac
$  ./macos-guest-virtualbox.sh

./macos-guest-virtualbox.sh: line 6: $'\r': command not found
./macos-guest-virtualbox.sh: line 15: $'\r': command not found
....

```
(Remove  \r , it's not supported)

**Comment by myspaghetti** [comment] 2021-01-21 12:29
Duplicate of issue #28 

>Won't fix; you need to choose the correct line endings for your terminal by yourself.

**Closed by myspaghetti** 2021-01-21 12:29 UTC
Labels: duplicate, non-script, won't fix

**Comment by Wheaties466** [comment] 2021-01-27 18:46
@MontrealSergiy If you install dos2unix on cygwin and do the following it will fix the line breaks.

https://superuser.com/questions/612435/cygwin-dos2unix-command-not-found

```
$ dos2unix.exe macos-guest-virtualbox.sh
dos2unix: converting file macos-guest-virtualbox.sh to Unix format...

mike ~/macos-virtualbox
$ ./
.git/                      README.md
LICENSE                    macos-guest-virtualbox.sh

mike ~/macos-virtualbox
$ ./macos-guest-virtualbox.sh

Push-button installer of macOS on VirtualBox

This script installs only open-source software and unmodified Apple binaries,
and requires about 50GB of available storage, of which 25GB are for temporary
installation files that may be deleted when the script is finished.

The script interacts with the virtual machine twice, please do not interact
with the virtual machine manually before the script is finished.

Documentation about optional configuration, iCloud and iMessage connectivity,
resuming the script by stages, and other topics can be viewed with the
following command:

  ./macos-guest-virtualbox.sh documentation | less -R

Press enter to review the script configuration

```
