### ISSUE TITLE
sed: RE error: illegal byte sequence 

### ISSUE THREAD

**Issue by itzvellodan** [myspaghetti/macos-virtualbox#315] opened 2020-10-12 12:29 UTC
![Screenshot from 2020-10-12 17-56-45](https://user-images.githubusercontent.com/46296179/95746598-afeb1d80-0cb4-11eb-828d-8a356d47e7fc.png)

**Comment by myspaghetti** [comment] 2020-10-12 12:39
Duplicate of #308 , closing as `won't fix` since I won't be implementing any hash checks or other file integrity checks.

**Closed by myspaghetti** 2020-10-12 12:39 UTC
Labels: duplicate
