### ISSUE TITLE
Syntax error when running script.

### ISSUE THREAD

**Issue by Ecstxsy** [myspaghetti/macos-virtualbox#457] opened 2021-04-28 20:11 UTC
Hello. Recently found this script which worked nicely on my linux machine, but as that is not my main PC, i tried running it on my main rig thats running Windows 10 Pro using Cygwin and got these errors. How do i fix them ?
![Screenshot_1](https://user-images.githubusercontent.com/37744158/116466355-0bf34900-a877-11eb-8063-7dc2123df051.png)

**Comment by myspaghetti** [comment] 2021-04-29 00:59
Duplicate of [#28](https://github.com/myspaghetti/macos-virtualbox/issues/238#issuecomment-645290351), resolved as `won't fix`. [Probably on installation, `git` was set to convert newline characters `LF` to `CRLF`](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings). While I can [configure the repository to override local Git configuration](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings#per-repository-settings) I feel like respecting local settings is the correct solution.

Configure git to keep line endings or [download the script manually](https://raw.githubusercontent.com/myspaghetti/macos-virtualbox/master/macos-guest-virtualbox.sh).

**Closed by myspaghetti** 2021-04-29 00:59 UTC
Labels: duplicate, won't fix
