### ISSUE TITLE
Exits after the second prompt to enter

### ISSUE THREAD

**Issue by no5764** [myspaghetti/macos-virtualbox#350] opened 2020-12-07 23:17 UTC
I have made sure to allocate enough space for the downloads and have run the script as an admin. However, after being prompted to press "enter to see configuration or CTRL+C to exit" the script terminates. Any thoughts?

**Comment by no5764** [comment] 2020-12-07 23:17
Using Windows 10  by the way.

**Comment by myspaghetti** [comment] 2020-12-08 04:54
The script is not meant to be run with elevated privileges, this creates permission issues with VirtualBox.

Please run the script with `bash -x macos-guest-virtualbox.sh` so you can see which command specifically fails. The script normally terminates with an actionable error message so if it doesn't tell you why it terminated there is probably some non-script error.

**Comment by StupidRepo** [comment] 2020-12-08 18:08
So I did the bash thing and got this:

`+ $'\r'
e.sh: line 6: $'\r': command not found
+ $'\r'
e.sh: line 15: $'\r': command not found
e.sh: line 16: syntax error near unexpected token `$'{\r''
'.sh: line 16: `function set_variables() {`

**Comment by StupidRepo** [comment] 2020-12-08 18:19
I renamed it to `e.sh` btw.

**Comment by no5764** [comment] 2020-12-08 18:28
If you open it in Vim you can replace those newlines by typing
" :%s/\r$//"
":x" to exit

**Comment by myspaghetti** [comment] 2020-12-08 19:32
Duplicate of #28

**Closed by myspaghetti** 2020-12-08 19:32 UTC
Labels: duplicate

**Comment by no5764** [comment] 2020-12-08 23:36
+ warning_color=''
+ highlight_color=''
+ low_contrast_color=''
+ default_color=''
+ check_shell
+ [[ -n 4.4.12(3)-release ]]
+ [[ -n '' ]]
+ [[ -n 4.4.12(3)-release ]]
+ [[ 4 -ge 5 ]]
+ [[ 4.4 =~ 4\.[3-9] ]]
+ stages='
    check_shell
    check_gnu_coreutils_prefix
    set_variables
    welcome
    check_dependencies
    prompt_delete_existing_vm
    create_vm
    check_default_virtual_machine
    prepare_macos_installation_files
    create_nvram_files
    create_macos_installation_files_viso
    configure_vm
    populate_basesystem_virtual_disk
    create_bootable_installer_virtual_disk
    populate_bootable_installer_virtual_disk
    create_target_virtual_disk
    populate_macos_target_disk
    prompt_delete_temporary_files
'
+ [[ -z '' ]]
+ for stage in ${stages}
+ check_shell
+ [[ -n 4.4.12(3)-release ]]
+ [[ -n '' ]]
+ [[ -n 4.4.12(3)-release ]]
+ [[ 4 -ge 5 ]]
+ [[ 4.4 =~ 4\.[3-9] ]]
+ for stage in ${stages}
+ check_gnu_coreutils_prefix
++ gcsplit --help
+ [[ -n '' ]]
+ for stage in ${stages}
+ set_variables
+ vm_name=macOS
+ macOS_release_name=Catalina
+ storage_size=80000
+ storage_format=vdi
+ cpu_count=2
+ memory_size=4096
+ gpu_vram=128
+ resolution=1280x800
+ DmiSystemFamily='MacBook Pro'
+ DmiSystemProduct=MacBookPro11,2
+ DmiSystemSerial=NO_DEVICE_SN
+ DmiSystemUuid=CAFECAFE-CAFE-CAFE-CAFE-DECAFFDECAFF
+ DmiBIOSVersion=string:MBP7.89
+ DmiOEMVBoxVer=string:1
+ DmiOEMVBoxRev=string:.23.45.6
+ DmiBoardProduct=Mac-3CBD00234E554E41
+ DmiBoardSerial=NO_LOGIC_BOARD_SN
+ MLB=NO_LOGIC_BOARD_SN
+ ROM='%aa*%bbg%cc%dd'
+ SYSTEM_UUID=aabbccddeeff00112233445566778899
+ SYSTEM_INTEGRITY_PROTECTION=10
+ [[ -r '' ]]
+ for stage in ${stages}
+ welcome
+ echo -ne '\nPush-button installer of macOS on VirtualBox
This script installs only open-source software and unmodified Apple binaries,
and requires about 50GB of available storage, of which 25GB are for temporary
installation files that may be deleted when the script is finished.
The script interacts with the virtual machine twice, please do not interact
with the virtual machine manually before the script is finished.
Documentation about optional configuration, iCloud and iMessage connectivity,
resuming the script by stages, and other topics can be viewed with the
following command:
'

Push-button installer of macOS on VirtualBox
This script installs only open-source software and unmodified Apple binaries,
and requires about 50GB of available storage, of which 25GB are for temporary
installation files that may be deleted when the script is finished.
The script interacts with the virtual machine twice, please do not interact
with the virtual machine manually before the script is finished.
Documentation about optional configuration, iCloud and iMessage connectivity,
resuming the script by stages, and other topics can be viewed with the
following command:
+ would_you_like_to_know_less
++ less --version
+ [[ -z less 551 (PCRE regular expressions)
Copyright (C) 1984-2019  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: http://www.greenwoodsoftware.com/less ]]
+ echo -e '  macos-guest-virtualbox.sh documentation | less -R'
  macos-guest-virtualbox.sh documentation | less -R
+ echo -ne '\nPress enter to review the script configuration'

Press enter to review the script configuration+ clear_input_buffer_then_read
+ read -d '' -r -t 0
+ [[ -t 1 ]]
+ read

This is what is returned when I enter "bash -x
 macos-guest-virtualbox.sh"

**Comment by myspaghetti** [comment] 2020-12-09 05:07
You are running the script on a non-interactive terminal. `[[ -t 1]]` fails because `stdin` is non-interactive. Run bash with the `-i` flag or run the script non-interactively if you're an advanced user.

**Comment by myspaghetti** [comment] 2020-12-09 05:14
You are running the script on a non-interactive terminal. `[[ -t 1]]` fails because `stdout` is non-interactive. Run bash with the `-i` flag or run the script non-interactively if you're an advanced user.
