### ISSUE TITLE
Stuck on Press Enter when the Language Window is Ready

### ISSUE THREAD

**Issue by darvyong** [myspaghetti/macos-virtualbox#267] opened 2020-07-17 11:51 UTC
Hi, I tried using this installer on my system today, and i get stuck on the following:

![Screenshot_1](https://user-images.githubusercontent.com/31510085/87783205-97f72f80-c866-11ea-813e-73f6effce223.png)

I'm not sure what's wrong, I tried repeating the process in another folder and it results in the same issue. Can you help with this?

I'm doing this on Ubuntu 20.04 LTS (Ryzen 5 2600 B450 Motherboard with 1TB NVMe SSD).
I hope that something can be done about this :(

**Comment by myspaghetti** [comment] 2020-07-17 13:05
Duplicate of issue #8. See the documentation section `CPU profiles and CPUID settings` as instructed by the script.

**Closed by myspaghetti** 2020-07-17 13:05 UTC
Labels: duplicate
