### ISSUE TITLE
Catalina can't get past terminal screen - Ubuntu 20.04, screenshot attached

### ISSUE THREAD

**Issue by Montecri** [myspaghetti/macos-virtualbox#263] opened 2020-07-09 22:47 UTC
Hi,

Trying to install Catalina under Ubuntu 20.04 but can't get past the attached terminal screen.

Thanks & Regards,

- Cristiano
![image](https://user-images.githubusercontent.com/38574378/87098097-f005b480-c21c-11ea-8d29-7782e91a2d4f.png)

**Comment by myspaghetti** [comment] 2020-07-10 06:05
Duplicate of [issue #63 "The script is not robust to errant keyboard keystrokes"](https://github.com/myspaghetti/macos-virtualbox/issues/63)

Somewhere on the host terminal some backspaces or other keystrokes were read, which interrupted the keystrokes sent to the VirtualBox VM. You can resume the script from the `populate_macos_target_disk` stage, or from the `populate_virtual_disks` if keystrokes were interrupted before.

**Closed by myspaghetti** 2020-07-10 06:05 UTC
Labels: duplicate
