### ISSUE TITLE
VirtualBox: "Host system reported disk full" 

### ISSUE THREAD

**Issue by danfuentes** [myspaghetti/macos-virtualbox#242] opened 2020-06-03 06:53 UTC
I've executed this script about 5-7x time and I seem to run into a different error message each time. The last 2-3 times I've executed the script I get the following message from VirtualBox indicating "Host system reported disk full. VM execution is suspended. You can resume after freeing some space".
![Image 6-3-20 at 2 46 AM](https://user-images.githubusercontent.com/42923035/83605143-655ad700-a545-11ea-94a5-1187b5ee9a8c.JPG)

I'm not sure was disk utilization it's referencing too as both the VirtualBox disk image and my onboard HDD have more than enough space.

Can anyone help me identify what I'm doing wrong or missing?

**Comment by myspaghetti** [comment] 2020-06-03 07:17
Hi, thanks for the bug report! Apple released a new version of the Catalina installer today, I'll investigate if it has anything to do with it. In the meantime, if you don't mind, please attach the file `macOS_troubleshoot.txt` that is created when running `./macos-guest-virtualbox.sh troubleshoot`

**Comment by myspaghetti** [comment] 2020-06-03 10:33
A default installation of Catalina now requires 50GB of storage, 25GB for the temporary files and 25GB for the target virtual disk image.

**Comment by dfuentes03** [comment] 2020-06-04 07:47
@myspaghetti I saw some commits recently regarding the additional storage required for catalina... has this issue since been solved?

Regardless, I tried running it just now and ran into the same issue. Here's the `macOS_troubleshoot.txt` log file requested: [macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/4728368/macOS_troubleshoot.txt)

**Comment by myspaghetti** [comment] 2020-06-04 08:43
The log shows that everything is configured correctly and runs fine... until the disk full error.

I was not able to reproduce the issue on macOS Catalina 10.15.5 19F101. Make sure the partition or volume where `Catalina bootable installer.vdi` and `macOS.vdi` are stored does have enough free space by executing in Terminal on the script's working directory `df -h .` (mind the `.` at the end)

Possibly VirtualBox tries to create a temporary file elsewhere and the macOS host prevents this for security reasons; try to allow VirtualBox full disk access in System Preferences > Security & Privacy > Privacy.
![privacy](https://user-images.githubusercontent.com/31696646/83734023-169d6200-a657-11ea-8956-383c2a25be23.png)

Another possibility is that the macOS host is having trouble with the dynamically allocated virtual disks. You can create fixed-size virtual disks, which will make the script take up about **110GB** by using [this modified script `macos-guest-virtualbox.sh.txt`](https://github.com/myspaghetti/macos-virtualbox/files/4728631/macos-guest-virtualbox.sh.txt), or by modifying the script yourself by replacing `--variant standard` with `--variant fixed` in lines 707 and 742.

**Comment by dfuentes03** [comment] 2020-06-04 09:55
> The log shows that everything is configured correctly and runs fine... until the disk full error.
> 
> I was not able to reproduce the issue on macOS Catalina 10.15.5 19F101. Make sure the partition or volume where `Catalina bootable installer.vdi` and `macOS.vdi` are stored does have enough free space by executing in Terminal on the script's working directory `df -h .` (mind the `.` at the end)
> 
> Possibly VirtualBox tries to create a temporary file elsewhere and the macOS host prevents this for security reasons; try to allow VirtualBox full disk access in System Preferences > Security & Privacy > Privacy.
> ![privacy](https://user-images.githubusercontent.com/31696646/83734023-169d6200-a657-11ea-8956-383c2a25be23.png)
> 
> Another possibility is that the macOS host is having trouble with the dynamically allocated virtual disks. You can create fixed-size virtual disks, which will make the script take up about **110GB** by using [this modified script `macos-guest-virtualbox.sh.txt`](https://github.com/myspaghetti/macos-virtualbox/files/4728631/macos-guest-virtualbox.sh.txt), or by modifying the script yourself by replacing `--variant standard` with `--variant fixed` in lines 707 and 742.

@myspaghetti Thanks for your prompt and courteous response. This was the resulting input after entering the command you recommended:
Should I try replacing ``--variant standard` with `--variant fixed` in lines 707 and 742 as recommend even after ur latest commits.

**Comment by myspaghetti** [comment] 2020-06-04 10:04
The latest commits only changed the documentation, the script still works exactly the same, and the line numbers. are the same. You should use `df -h .` to make sure the partition or volume have enough free space. If there's enough free space you should give VirtualBox full disk access (you can revoke it later) and if VirtualBox still reports "disk full" you should use `--variant fixed`

If the issue still persists you will have to file a bug report with Oracle.

**Comment by dfuentes03** [comment] 2020-06-04 10:16
When should I that command with the referenced arguments? Before install, during install, or a failed attempt to install is attempted..

**Comment by myspaghetti** [comment] 2020-06-04 10:33
1. On the macOS host, in Terminal, on the script's working directory, run `df -h .`
1.1. If there aren't 50GB available, there's your problem.
2. If `df -h .` reports over 50GB available, try giving VirtualBox Full Disk Access then run the script.
3. If VirtualBox reports "disk full" even with Full Disk Access, either edit the script at lines 707 and 742 replacing `--variant standard` with `--variant fixed`, or [run the attached edited script](https://github.com/myspaghetti/macos-virtualbox/files/4728631/macos-guest-virtualbox.sh.txt) which is already edited with `--variant fixed`. This will require **110GB** of available storage instead of the previous 50GB. Make sure the working directory has 110GB of available storage with `df -h .` then run the edited script.
4. If giving VirtualBox Full Disk Access and using `--variant fixed` doesn't work, then you'll have to investigate the issue further by yourself.

**Comment by myspaghetti** [comment] 2020-06-11 01:41
Closing until further information is provided.

**Closed by myspaghetti** 2020-06-11 01:41 UTC
Labels: bug
