### ISSUE TITLE
Script does not work anymore

### ISSUE THREAD

**Issue by leoheck** [myspaghetti/macos-virtualbox#591] opened 2022-03-18 17:09 UTC
I was trying to run the script multiple times, to test things. Now I am getting this. Even after restarting the computer. 
Do you have any idea how to fix this?

```
stage: configure_vm

Error: Could not configure virtual machine "macOS".
If the VM is powered on, power off the virtual machine and resume the script or
execute the stage configure_vm

Exiting.
```

**Comment by leoheck** [comment] 2022-03-18 17:11
I changed some parameters too. Maybe they are the issue.
![image](https://user-images.githubusercontent.com/1277920/159050597-ff1e7e42-c69c-4ddb-b1b0-61e5ad67e1dd.png)

**Comment by myspaghetti** [comment] 2022-03-21 13:22
Probably a duplicate of #590 , I will investigate but probably not in the near future, sorry.

**Comment by leoheck** [comment] 2022-03-21 14:52
The issue is this one
```
VBoxManage: error: Invalid parameter 'Core'
```

When I am forcing another cpu-profile with this flag
```
--cpu-profile "Intel Core i7-6700K
```

On this command here
```
VBoxManage modifyvm "${vm_name}" --cpus "${cpu_count}"...
```

**Comment by Masamune3210** [comment] 2022-03-21 21:47
You are missing a closing quotation, so the script is trying to take the Core in Intel Core as an argument

**Comment by leoheck** [comment] 2022-03-21 22:34
Ah, yeah. Good catch, however, the issue was only here which I am fixing, on my script, it is/was ok. It is not working with variables yet.

**Closed** 2022-04-02 12:32 UTC
Labels: non-script
